USE ecommerce;

-- =====================================================
-- 1. Check Sample Data
-- Purpose: View first 10 records of the dataset.
-- =====================================================

SELECT *
FROM orders
LIMIT 10;

-- =====================================================
-- 2. Total Revenue
-- Purpose: Calculate total sales revenue.
-- =====================================================

SELECT
ROUND(SUM(TotalPrice),2) AS Total_Revenue
FROM orders;

-- =====================================================
-- 3. Total Orders
-- Purpose: Count unique orders.
-- =====================================================

SELECT
COUNT(DISTINCT InvoiceNo) AS Total_Orders
FROM orders;

-- =====================================================
-- 4. Total Customers
-- Purpose: Count unique customers.
-- =====================================================

SELECT
COUNT(DISTINCT CustomerID) AS Total_Customers
FROM orders;

-- =====================================================
-- 5. Total Products
-- Purpose: Count unique products.
-- =====================================================

SELECT
COUNT(DISTINCT StockCode) AS Total_Products
FROM orders;

-- =====================================================
-- 6. Top 10 Products by Revenue
-- Purpose: Identify highest revenue generating products.
-- =====================================================

SELECT
Description,
ROUND(SUM(TotalPrice),2) AS Revenue
FROM orders
GROUP BY Description
ORDER BY Revenue DESC
LIMIT 10;

-- =====================================================
-- 7. Top 10 Products by Quantity Sold
-- Purpose: Identify most sold products.
-- =====================================================

SELECT
Description,
SUM(Quantity) AS Quantity_Sold
FROM orders
GROUP BY Description
ORDER BY Quantity_Sold DESC
LIMIT 10;

-- =====================================================
-- 8. Sales by Country
-- Purpose: Analyze revenue generated by each country.
-- =====================================================

SELECT
Country,
ROUND(SUM(TotalPrice),2) AS Revenue
FROM orders
GROUP BY Country
ORDER BY Revenue DESC;

-- =====================================================
-- 9. Monthly Sales Trend
-- Purpose: Analyze monthly sales performance.
-- =====================================================

SELECT
DATE_FORMAT(InvoiceDate,'%Y-%m') AS Month,
ROUND(SUM(TotalPrice),2) AS Revenue
FROM orders
GROUP BY Month
ORDER BY Month;

-- =====================================================
-- 10. Top 10 Customers by Spending
-- Purpose: Identify customers generating highest revenue.
-- =====================================================

SELECT
CustomerID,
ROUND(SUM(TotalPrice),2) AS Total_Spending
FROM orders
GROUP BY CustomerID
ORDER BY Total_Spending DESC
LIMIT 10;

-- =====================================================
-- 11. Average Order Value
-- Purpose: Calculate the average value of each order.
-- =====================================================

SELECT
ROUND(
SUM(TotalPrice) / COUNT(DISTINCT InvoiceNo),2
) AS Avg_Order_Value
FROM orders;

-- =====================================================
-- 12. Orders per Country
-- Purpose: Count total orders placed from each country.
-- =====================================================

SELECT
Country,
COUNT(DISTINCT InvoiceNo) AS Total_Orders
FROM orders
GROUP BY Country
ORDER BY Total_Orders DESC;

-- =====================================================
-- 13. Highest Revenue Month
-- Purpose: Find the month with the highest sales.
-- =====================================================

SELECT
DATE_FORMAT(InvoiceDate,'%Y-%m') AS Month,
ROUND(SUM(TotalPrice),2) AS Revenue
FROM orders
GROUP BY Month
ORDER BY Revenue DESC
LIMIT 1;

-- =====================================================
-- 14. Most Expensive Products
-- Purpose: Find products with the highest unit price.
-- =====================================================

SELECT
Description,
MAX(UnitPrice) AS Highest_Price
FROM orders
GROUP BY Description
ORDER BY Highest_Price DESC
LIMIT 10;

-- =====================================================
-- 15. Revenue Contribution by Country
-- Purpose: Find each country's contribution to total revenue.
-- =====================================================

SELECT
Country,
ROUND(SUM(TotalPrice),2) AS Revenue,
ROUND(
(SUM(TotalPrice) /
(SELECT SUM(TotalPrice) FROM orders))*100,2
) AS Revenue_Percentage
FROM orders
GROUP BY Country
ORDER BY Revenue DESC;

-- =====================================================
-- 16. Products Sold More Than 1000 Units
-- Purpose: Find high-demand products.
-- =====================================================

SELECT
Description,
SUM(Quantity) AS Quantity_Sold
FROM orders
GROUP BY Description
HAVING SUM(Quantity) > 1000
ORDER BY Quantity_Sold DESC;

-- =====================================================
-- 17. Customer Category Based on Spending
-- Purpose: Categorize customers using CASE.
-- =====================================================

SELECT
CustomerID,
ROUND(SUM(TotalPrice),2) AS Total_Spending,
CASE
WHEN SUM(TotalPrice) >= 10000 THEN 'Premium'
WHEN SUM(TotalPrice) >= 5000 THEN 'Gold'
WHEN SUM(TotalPrice) >= 1000 THEN 'Silver'
ELSE 'Regular'
END AS Customer_Category
FROM orders
GROUP BY CustomerID
ORDER BY Total_Spending DESC;

-- =====================================================
-- 18. Products with Above Average Revenue
-- Purpose: Find products performing above average.
-- =====================================================

SELECT
Description,
ROUND(SUM(TotalPrice),2) AS Revenue
FROM orders
GROUP BY Description
HAVING Revenue >
(
SELECT AVG(ProductRevenue)
FROM
(
SELECT SUM(TotalPrice) AS ProductRevenue
FROM orders
GROUP BY Description
) AS AvgRevenue
)
ORDER BY Revenue DESC;

-- =====================================================
-- 19. Top Revenue Invoice
-- Purpose: Find invoices generating the highest revenue.
-- =====================================================

SELECT
InvoiceNo,
ROUND(SUM(TotalPrice),2) AS Invoice_Revenue
FROM orders
GROUP BY InvoiceNo
ORDER BY Invoice_Revenue DESC
LIMIT 10;

-- =====================================================
-- 20. Average Revenue by Country
-- Purpose: Compare average sales across countries.
-- =====================================================

SELECT
Country,
ROUND(AVG(TotalPrice),2) AS Avg_Revenue
FROM orders
GROUP BY Country
ORDER BY Avg_Revenue DESC;